-- Drop existing tables to start fresh if needed
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS slots CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users Table (Handles Patients, Doctors, Admins)
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK(role IN ('patient', 'doctor', 'admin')),
    specialty VARCHAR(100), -- Nullable, used for Doctors
    contact VARCHAR(20) NOT NULL,
    is_available BOOLEAN DEFAULT TRUE -- Used for Doctors duty status
);

-- Doctor Slots Table
CREATE TABLE slots (
    id SERIAL PRIMARY KEY,
    doctor_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slot_time VARCHAR(50) NOT NULL, -- e.g. "2026-08-25 10:00 AM"
    is_booked BOOLEAN DEFAULT FALSE
);

-- Appointments Table with detailed tracking & summaries
CREATE TABLE appointments (
    id SERIAL PRIMARY KEY,
    patient_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    doctor_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slot_id INT NOT NULL REFERENCES slots(id) ON DELETE CASCADE,
    problem_description TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'booked' CHECK(status IN ('booked', 'cancelled', 'completed')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    pre_visit_summary TEXT,  -- Generated by AI
    post_visit_summary TEXT, -- Generated by AI
    prescription TEXT        -- Saved by Doctor
);
